#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : intel-graphics-compiler
Version  : i.2019.02.25
Release  : 5
URL      : https://github.com/intel/intel-graphics-compiler/archive/igc_release_2019-02-25.tar.gz
Source0  : https://github.com/intel/intel-graphics-compiler/archive/igc_release_2019-02-25.tar.gz
Summary  : Intel Graphics Compiler for OpenCL
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: intel-graphics-compiler-bin = %{version}-%{release}
Requires: intel-graphics-compiler-lib = %{version}-%{release}
Requires: intel-graphics-compiler-license = %{version}-%{release}
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : flex
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : llvm-extras
BuildRequires : nose
Patch1: warn-as-error-if-evil.patch
Patch2: print-is-a-function-in-python.patch
Patch3: add-static.patch

%description
IGA - Intel Graphics Assembler
[Build On Windows]
Prerequisite:
Visaul Studio version >= 2012
CMake version >= 2.8

%package bin
Summary: bin components for the intel-graphics-compiler package.
Group: Binaries
Requires: intel-graphics-compiler-license = %{version}-%{release}

%description bin
bin components for the intel-graphics-compiler package.


%package dev
Summary: dev components for the intel-graphics-compiler package.
Group: Development
Requires: intel-graphics-compiler-lib = %{version}-%{release}
Requires: intel-graphics-compiler-bin = %{version}-%{release}
Provides: intel-graphics-compiler-devel = %{version}-%{release}
Requires: intel-graphics-compiler = %{version}-%{release}

%description dev
dev components for the intel-graphics-compiler package.


%package lib
Summary: lib components for the intel-graphics-compiler package.
Group: Libraries
Requires: intel-graphics-compiler-license = %{version}-%{release}

%description lib
lib components for the intel-graphics-compiler package.


%package license
Summary: license components for the intel-graphics-compiler package.
Group: Default

%description license
license components for the intel-graphics-compiler package.


%prep
%setup -q -n intel-graphics-compiler-igc_release_2019-02-25
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552237876
unset LD_AS_NEEDED
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  
popd

%install
export SOURCE_DATE_EPOCH=1552237876
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/intel-graphics-compiler
cp IGC/BiFModule/Implementation/ExternalLibraries/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/intel-graphics-compiler/IGC_BiFModule_Implementation_ExternalLibraries_libclc_LICENSE.TXT
cp third_party/opencl_headers/LICENSE %{buildroot}/usr/share/package-licenses/intel-graphics-compiler/third_party_opencl_headers_LICENSE
pushd clr-build
%make_install
popd
## install_append content
mv %{buildroot}/usr/lib/*so %{buildroot}/usr/lib64/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/GenX_IR
/usr/bin/iga64

%files dev
%defattr(-,root,root,-)
/usr/include/igc/GlobalData.h
/usr/include/igc/MoveStaticAllocas.h
/usr/include/igc/OCL/BuiltinResource.h
/usr/include/igc/OCL/CommandStream/SamplerTypes.h
/usr/include/igc/OCL/CommandStream/SurfaceTypes.h
/usr/include/igc/OCL/LoadBuffer.h
/usr/include/igc/OCL/Patch/patch_parser.h
/usr/include/igc/OCL/Platform/cmd_3d_def_g8.h
/usr/include/igc/OCL/Platform/cmd_3d_enum_g8.h
/usr/include/igc/OCL/Platform/cmd_3d_init_g8.h
/usr/include/igc/OCL/Platform/cmd_enum.h
/usr/include/igc/OCL/Platform/cmd_enum_g8.h
/usr/include/igc/OCL/Platform/cmd_init_g8.h
/usr/include/igc/OCL/Platform/cmd_media_caps_g8.h
/usr/include/igc/OCL/Platform/cmd_media_def_g8.h
/usr/include/igc/OCL/Platform/cmd_media_enum_g8.h
/usr/include/igc/OCL/Platform/cmd_media_init_g8.h
/usr/include/igc/OCL/Platform/cmd_mi_def_g8.h
/usr/include/igc/OCL/Platform/cmd_mi_enum_g8.h
/usr/include/igc/OCL/Platform/cmd_mi_init_g8.h
/usr/include/igc/OCL/Platform/cmd_parser_g8.h
/usr/include/igc/OCL/Platform/cmd_shared_def_g8.h
/usr/include/igc/OCL/Platform/cmd_shared_enum_g8.h
/usr/include/igc/OCL/Platform/cmd_shared_init_g8.h
/usr/include/igc/OCL/Resource/BuiltinResource.h
/usr/include/igc/OCL/TB/igc_tb.h
/usr/include/igc/OCL/sp/gtpin_igc_ocl.h
/usr/include/igc/OCL/sp/sp_convert_g8.h
/usr/include/igc/OCL/sp/sp_debug.h
/usr/include/igc/OCL/sp/sp_g8.h
/usr/include/igc/OCL/sp/sp_types.h
/usr/include/igc/OCL/sp/spp_g8.h
/usr/include/igc/OCL/util/BinaryStream.h
/usr/include/igc/PatchList.h
/usr/include/igc/SPIRV/Mangler/ParameterType.h
/usr/include/igc/SPIRV/Mangler/Refcount.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.0/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.0/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.0/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.1/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.1/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.1/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.2/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.2/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/1.2/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/unified1/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/unified1/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/include/spirv/unified1/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/tools/buildHeaders/header.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/tools/buildHeaders/jsonToSpirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/tools/buildHeaders/jsoncpp/dist/json/json-forwards.h
/usr/include/igc/SPIRV/SPIRV-Tools/external/SPIRV-Headers/tools/buildHeaders/jsoncpp/dist/json/json.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv-tools/libspirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.0/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.0/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.0/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.1/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.1/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.1/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.2/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.2/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/1.2/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/unified1/GLSL.std.450.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/unified1/OpenCL.std.h
/usr/include/igc/SPIRV/SPIRV-Tools/include/spirv/unified1/spirv.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/assembly_grammar.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/binary.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/cfa.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/diagnostic.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/disassemble.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/enum_set.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/enum_string_mapping.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/ext_inst.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/extensions.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/id_descriptor.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/instruction.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/latest_version_glsl_std_450_header.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/latest_version_opencl_std_header.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/latest_version_spirv_header.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/macro.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/name_mapper.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/opcode.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/operand.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/parsed_operand.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/print.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_constant.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_definition.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_endian.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_optimizer_options.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_target_env.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/spirv_validator_options.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/table.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/text.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/text_handler.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/bit_vector.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/bitutils.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/hex_float.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/ilist.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/ilist_node.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/make_unique.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/parse_number.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/small_vector.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/string_utils.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/util/timer.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/basic_block.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/construct.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/decoration.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/function.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/instruction.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/validate.h
/usr/include/igc/SPIRV/SPIRV-Tools/source/val/validation_state.h
/usr/include/igc/SPIRV/SPIRVException.h
/usr/include/igc/SPIRV/SPIRVInternal.h
/usr/include/igc/SPIRV/SPIRVconsum.h
/usr/include/igc/SPIRV/libSPIRV/OpenCL.std.h
/usr/include/igc/SPIRV/libSPIRV/OpenCL.stdfuncs.h
/usr/include/igc/SPIRV/libSPIRV/SPIRV.DebugInfo.h
/usr/include/igc/SPIRV/libSPIRV/SPIRV.DebugInfofuncs.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVBasicBlock.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVBuiltinEnum.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVDebug.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVDebugInfoExt.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVDecorate.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVEntry.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVEnum.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVError.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVErrorEnum.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVExtInst.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVFunction.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVInstruction.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVModule.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVOpCode.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVOpCodeEnum.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVStream.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVType.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVUtil.h
/usr/include/igc/SPIRV/libSPIRV/SPIRVValue.h
/usr/include/igc/TranslationBlock.h
/usr/include/igc/Upgrader/Upgrader.h
/usr/include/igc/Upgrader/llvm4/BitcodeReader.h
/usr/include/igc/Upgrader/llvm4/MetadataLoader.h
/usr/include/igc/Upgrader/llvm4/Upgrader.h
/usr/include/igc/Upgrader/llvm4/ValueList.h
/usr/include/igc/Upgrader/llvm7/BitcodeReader.h
/usr/include/igc/Upgrader/llvm7/MetadataLoader.h
/usr/include/igc/Upgrader/llvm7/Upgrader.h
/usr/include/igc/Upgrader/llvm7/ValueList.h
/usr/include/igc/Upgrader/llvm8/BitcodeReader.h
/usr/include/igc/Upgrader/llvm8/MetadataLoader.h
/usr/include/igc/Upgrader/llvm8/Upgrader.h
/usr/include/igc/Upgrader/llvm8/ValueList.h
/usr/include/igc/cif/cif/builtins/builtins_registry.h
/usr/include/igc/cif/cif/builtins/memory/buffer/buffer.h
/usr/include/igc/cif/cif/builtins/memory/buffer/impl/buffer_impl.h
/usr/include/igc/cif/cif/common/cif.h
/usr/include/igc/cif/cif/common/cif_main.h
/usr/include/igc/cif/cif/common/coder.h
/usr/include/igc/cif/cif/common/compatibility.h
/usr/include/igc/cif/cif/common/id.h
/usr/include/igc/cif/cif/common/library_api.h
/usr/include/igc/cif/cif/common/library_handle.h
/usr/include/igc/cif/cif/export/build/binary_version.h
/usr/include/igc/cif/cif/export/cif_impl.h
/usr/include/igc/cif/cif/export/cif_main_impl.h
/usr/include/igc/cif/cif/export/interface_creator.h
/usr/include/igc/cif/cif/export/library_api.h
/usr/include/igc/cif/cif/export/muiltiversion.h
/usr/include/igc/cif/cif/export/pimpl_base.h
/usr/include/igc/cif/cif/export/registry.h
/usr/include/igc/cif/cif/helpers/error.h
/usr/include/igc/cif/cif/helpers/memory.h
/usr/include/igc/cif/cif/import/cif_main.h
/usr/include/igc/cif/cif/import/library_api.h
/usr/include/igc/cif/cif/macros/disable.h
/usr/include/igc/cif/cif/macros/enable.h
/usr/include/igc/cif/cif/os/lin/lin_library_handle.h
/usr/include/igc/cif/cif/os/win/win_library_handle.h
/usr/include/igc/igc.opencl.h
/usr/include/igc/ocl_igc_interface/code_type.h
/usr/include/igc/ocl_igc_interface/fcl_ocl_device_ctx.h
/usr/include/igc/ocl_igc_interface/fcl_ocl_translation_ctx.h
/usr/include/igc/ocl_igc_interface/gt_system_info.h
/usr/include/igc/ocl_igc_interface/igc_features_and_workarounds.h
/usr/include/igc/ocl_igc_interface/igc_ocl_device_ctx.h
/usr/include/igc/ocl_igc_interface/igc_ocl_translation_ctx.h
/usr/include/igc/ocl_igc_interface/impl/fcl_ocl_device_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/fcl_ocl_translation_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/gt_system_info_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_features_and_workarounds_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_ocl_device_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_ocl_translation_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/ocl_gen_binary_impl.h
/usr/include/igc/ocl_igc_interface/impl/ocl_translation_output_impl.h
/usr/include/igc/ocl_igc_interface/impl/platform_impl.h
/usr/include/igc/ocl_igc_interface/ocl_gen_binary.h
/usr/include/igc/ocl_igc_interface/ocl_translation_output.h
/usr/include/igc/ocl_igc_interface/platform.h
/usr/include/igc/ocl_igc_interface/platform_helper.h
/usr/include/igc/ocl_igc_shared/device_enqueue/DeviceEnqueueInternalTypes.h
/usr/include/igc/ocl_igc_shared/device_enqueue/device_enqueue_internal_types.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g10.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g7.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g8.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g9.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_list.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_shared.h
/usr/include/igc/ocl_igc_shared/executable_format/program_debug_data.h
/usr/include/igc/ocl_igc_shared/gtpin/gtpin_driver_common.h
/usr/include/igc/ocl_igc_shared/gtpin/gtpin_ocl_interface.h
/usr/lib64/pkgconfig/igc-opencl.pc

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/libcommon_clang.so
/usr/lib64/libiga64.so
/usr/lib64/libigc.so
/usr/lib64/libigdfcl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/intel-graphics-compiler/IGC_BiFModule_Implementation_ExternalLibraries_libclc_LICENSE.TXT
/usr/share/package-licenses/intel-graphics-compiler/third_party_opencl_headers_LICENSE
